Negotiation&admin
ZaragozaEnJuego/client pull request #27
Opened 2023-04-07 20:43 UTC by ibon-sk

2023-04-07 23:40 UTC, arejula27 requested changes
Hay varias funcionalidades en un unico merge. Si puedes separa por un lado la negociación y por otro el admin, de tal forma que los commit son más atomicos. Si es mucho inconveniente dejalo en uno y para los proximos desarrolla en distintas ramas. gj 💪

2023-04-07 23:40 UTC, arejula27 commented on src/core/negotiations/domain/model.ts
> +    property: Propertie;
Es mejor que sea unicamente el id de la propiedad

2023-04-07 23:40 UTC, arejula27 commented on src/core/negotiations/domain/model.ts
> +    id: number;
En mongo los id tienen letras

2023-04-07 23:40 UTC, arejula27 commented on package.json
>    }
es realmente necesario cambiar la version inicial?

2023-04-07 23:40 UTC, arejula27 commented on src/core/user/domain/model.ts
> +export type Access = 'Activado' | 'Desactivado'
esta en español, mientras el resto es en ingles

2023-04-07 23:40 UTC, arejula27 commented on src/core/user/domain/model.ts
> +    id: number;
mongo _id usa string

2023-04-07 23:40 UTC, arejula27 commented on src/core/user/domain/model.ts
> +export type User = {
Tipo User no es el mismo que landlord? si es así escoger un unico

2023-04-07 23:40 UTC, arejula27 commented on src/router.tsx
> +  },
Tendria que estar en un array de admin unicamente, ya que los permisos son distitnos

2023-04-07 23:40 UTC, arejula27 commented on src/ui/pages/LoginPage.tsx
> +        </div>
Esto deberia ser el mismo boton pero la redireccion distinta en función de si el back dice k es admin o no

2023-04-07 23:40 UTC, arejula27 commented on src/ui/pages/NegotiationPage.tsx
> +  }, []);
Puede ser el mismo useEffect. Cada use effect suelel tener un trigger, cuando es el mismo por legibilidad es mejor que este junto. Se ponen varios cuando el trigger cambia

2023-04-08 17:11 UTC, ibon-sk commented on package.json
>    }
Esto debí de cambiarlo cuando creé el Docker e hice el primer yarn install, pero realmente no es necesario. Ya está solucionado en mi local.

2023-04-08 18:43 UTC, closed without merging